/**
 * Full world country list with Arabic names, ISO codes, dial codes and flags.
 * Used for phone-number sign up / sign in and for the profile country field.
 */

export type Country = {
  code: string;
  name: string;
  dial: string;
  flag: string;
};

export const COUNTRIES: Country[] = [
  { code: "EG", name: "مصر", dial: "20", flag: "🇪🇬" },
  { code: "SA", name: "السعودية", dial: "966", flag: "🇸🇦" },
  { code: "AE", name: "الإمارات", dial: "971", flag: "🇦🇪" },
  { code: "KW", name: "الكويت", dial: "965", flag: "🇰🇼" },
  { code: "QA", name: "قطر", dial: "974", flag: "🇶🇦" },
  { code: "BH", name: "البحرين", dial: "973", flag: "🇧🇭" },
  { code: "OM", name: "عُمان", dial: "968", flag: "🇴🇲" },
  { code: "JO", name: "الأردن", dial: "962", flag: "🇯🇴" },
  { code: "LB", name: "لبنان", dial: "961", flag: "🇱🇧" },
  { code: "SY", name: "سوريا", dial: "963", flag: "🇸🇾" },
  { code: "IQ", name: "العراق", dial: "964", flag: "🇮🇶" },
  { code: "PS", name: "فلسطين", dial: "970", flag: "🇵🇸" },
  { code: "YE", name: "اليمن", dial: "967", flag: "🇾🇪" },
  { code: "MA", name: "المغرب", dial: "212", flag: "🇲🇦" },
  { code: "DZ", name: "الجزائر", dial: "213", flag: "🇩🇿" },
  { code: "TN", name: "تونس", dial: "216", flag: "🇹🇳" },
  { code: "LY", name: "ليبيا", dial: "218", flag: "🇱🇾" },
  { code: "SD", name: "السودان", dial: "249", flag: "🇸🇩" },
  { code: "MR", name: "موريتانيا", dial: "222", flag: "🇲🇷" },
  { code: "SO", name: "الصومال", dial: "252", flag: "🇸🇴" },
  { code: "DJ", name: "جيبوتي", dial: "253", flag: "🇩🇯" },
  { code: "KM", name: "جزر القمر", dial: "269", flag: "🇰🇲" },
  { code: "TR", name: "تركيا", dial: "90", flag: "🇹🇷" },
  { code: "AF", name: "أفغانستان", dial: "93", flag: "🇦🇫" },
  { code: "AL", name: "ألبانيا", dial: "355", flag: "🇦🇱" },
  { code: "AD", name: "أندورا", dial: "376", flag: "🇦🇩" },
  { code: "AO", name: "أنغولا", dial: "244", flag: "🇦🇴" },
  { code: "AG", name: "أنتيغوا وبربودا", dial: "1268", flag: "🇦🇬" },
  { code: "AR", name: "الأرجنتين", dial: "54", flag: "🇦🇷" },
  { code: "AM", name: "أرمينيا", dial: "374", flag: "🇦🇲" },
  { code: "AU", name: "أستراليا", dial: "61", flag: "🇦🇺" },
  { code: "AT", name: "النمسا", dial: "43", flag: "🇦🇹" },
  { code: "AZ", name: "أذربيجان", dial: "994", flag: "🇦🇿" },
  { code: "BS", name: "الباهاما", dial: "1242", flag: "🇧🇸" },
  { code: "BD", name: "بنغلاديش", dial: "880", flag: "🇧🇩" },
  { code: "BB", name: "بربادوس", dial: "1246", flag: "🇧🇧" },
  { code: "BY", name: "بيلاروسيا", dial: "375", flag: "🇧🇾" },
  { code: "BE", name: "بلجيكا", dial: "32", flag: "🇧🇪" },
  { code: "BZ", name: "بليز", dial: "501", flag: "🇧🇿" },
  { code: "BJ", name: "بنين", dial: "229", flag: "🇧🇯" },
  { code: "BT", name: "بوتان", dial: "975", flag: "🇧🇹" },
  { code: "BO", name: "بوليفيا", dial: "591", flag: "🇧🇴" },
  { code: "BA", name: "البوسنة والهرسك", dial: "387", flag: "🇧🇦" },
  { code: "BW", name: "بوتسوانا", dial: "267", flag: "🇧🇼" },
  { code: "BR", name: "البرازيل", dial: "55", flag: "🇧🇷" },
  { code: "BN", name: "بروناي", dial: "673", flag: "🇧🇳" },
  { code: "BG", name: "بلغاريا", dial: "359", flag: "🇧🇬" },
  { code: "BF", name: "بوركينا فاسو", dial: "226", flag: "🇧🇫" },
  { code: "BI", name: "بوروندي", dial: "257", flag: "🇧🇮" },
  { code: "KH", name: "كمبوديا", dial: "855", flag: "🇰🇭" },
  { code: "CM", name: "الكاميرون", dial: "237", flag: "🇨🇲" },
  { code: "CA", name: "كندا", dial: "1", flag: "🇨🇦" },
  { code: "CV", name: "الرأس الأخضر", dial: "238", flag: "🇨🇻" },
  { code: "CF", name: "أفريقيا الوسطى", dial: "236", flag: "🇨🇫" },
  { code: "TD", name: "تشاد", dial: "235", flag: "🇹🇩" },
  { code: "CL", name: "تشيلي", dial: "56", flag: "🇨🇱" },
  { code: "CN", name: "الصين", dial: "86", flag: "🇨🇳" },
  { code: "CO", name: "كولومبيا", dial: "57", flag: "🇨🇴" },
  { code: "CG", name: "الكونغو", dial: "242", flag: "🇨🇬" },
  { code: "CD", name: "الكونغو الديمقراطية", dial: "243", flag: "🇨🇩" },
  { code: "CR", name: "كوستاريكا", dial: "506", flag: "🇨🇷" },
  { code: "CI", name: "ساحل العاج", dial: "225", flag: "🇨🇮" },
  { code: "HR", name: "كرواتيا", dial: "385", flag: "🇭🇷" },
  { code: "CU", name: "كوبا", dial: "53", flag: "🇨🇺" },
  { code: "CY", name: "قبرص", dial: "357", flag: "🇨🇾" },
  { code: "CZ", name: "التشيك", dial: "420", flag: "🇨🇿" },
  { code: "DK", name: "الدنمارك", dial: "45", flag: "🇩🇰" },
  { code: "DM", name: "دومينيكا", dial: "1767", flag: "🇩🇲" },
  { code: "DO", name: "الدومينيكان", dial: "1809", flag: "🇩🇴" },
  { code: "EC", name: "الإكوادور", dial: "593", flag: "🇪🇨" },
  { code: "SV", name: "السلفادور", dial: "503", flag: "🇸🇻" },
  { code: "GQ", name: "غينيا الاستوائية", dial: "240", flag: "🇬🇶" },
  { code: "ER", name: "إريتريا", dial: "291", flag: "🇪🇷" },
  { code: "EE", name: "إستونيا", dial: "372", flag: "🇪🇪" },
  { code: "SZ", name: "إسواتيني", dial: "268", flag: "🇸🇿" },
  { code: "ET", name: "إثيوبيا", dial: "251", flag: "🇪🇹" },
  { code: "FJ", name: "فيجي", dial: "679", flag: "🇫🇯" },
  { code: "FI", name: "فنلندا", dial: "358", flag: "🇫🇮" },
  { code: "FR", name: "فرنسا", dial: "33", flag: "🇫🇷" },
  { code: "GA", name: "الغابون", dial: "241", flag: "🇬🇦" },
  { code: "GM", name: "غامبيا", dial: "220", flag: "🇬🇲" },
  { code: "GE", name: "جورجيا", dial: "995", flag: "🇬🇪" },
  { code: "DE", name: "ألمانيا", dial: "49", flag: "🇩🇪" },
  { code: "GH", name: "غانا", dial: "233", flag: "🇬🇭" },
  { code: "GR", name: "اليونان", dial: "30", flag: "🇬🇷" },
  { code: "GD", name: "غرينادا", dial: "1473", flag: "🇬🇩" },
  { code: "GT", name: "غواتيمالا", dial: "502", flag: "🇬🇹" },
  { code: "GN", name: "غينيا", dial: "224", flag: "🇬🇳" },
  { code: "GW", name: "غينيا بيساو", dial: "245", flag: "🇬🇼" },
  { code: "GY", name: "غيانا", dial: "592", flag: "🇬🇾" },
  { code: "HT", name: "هايتي", dial: "509", flag: "🇭🇹" },
  { code: "HN", name: "هندوراس", dial: "504", flag: "🇭🇳" },
  { code: "HK", name: "هونغ كونغ", dial: "852", flag: "🇭🇰" },
  { code: "HU", name: "هنغاريا", dial: "36", flag: "🇭🇺" },
  { code: "IS", name: "آيسلندا", dial: "354", flag: "🇮🇸" },
  { code: "IN", name: "الهند", dial: "91", flag: "🇮🇳" },
  { code: "ID", name: "إندونيسيا", dial: "62", flag: "🇮🇩" },
  { code: "IR", name: "إيران", dial: "98", flag: "🇮🇷" },
  { code: "IE", name: "أيرلندا", dial: "353", flag: "🇮🇪" },
  { code: "IT", name: "إيطاليا", dial: "39", flag: "🇮🇹" },
  { code: "JM", name: "جامايكا", dial: "1876", flag: "🇯🇲" },
  { code: "JP", name: "اليابان", dial: "81", flag: "🇯🇵" },
  { code: "KZ", name: "كازاخستان", dial: "7", flag: "🇰🇿" },
  { code: "KE", name: "كينيا", dial: "254", flag: "🇰🇪" },
  { code: "KI", name: "كيريباتي", dial: "686", flag: "🇰🇮" },
  { code: "KG", name: "قيرغيزستان", dial: "996", flag: "🇰🇬" },
  { code: "LA", name: "لاوس", dial: "856", flag: "🇱🇦" },
  { code: "LV", name: "لاتفيا", dial: "371", flag: "🇱🇻" },
  { code: "LS", name: "ليسوتو", dial: "266", flag: "🇱🇸" },
  { code: "LR", name: "ليبيريا", dial: "231", flag: "🇱🇷" },
  { code: "LI", name: "ليختنشتاين", dial: "423", flag: "🇱🇮" },
  { code: "LT", name: "ليتوانيا", dial: "370", flag: "🇱🇹" },
  { code: "LU", name: "لوكسمبورغ", dial: "352", flag: "🇱🇺" },
  { code: "MG", name: "مدغشقر", dial: "261", flag: "🇲🇬" },
  { code: "MW", name: "مالاوي", dial: "265", flag: "🇲🇼" },
  { code: "MY", name: "ماليزيا", dial: "60", flag: "🇲🇾" },
  { code: "MV", name: "المالديف", dial: "960", flag: "🇲🇻" },
  { code: "ML", name: "مالي", dial: "223", flag: "🇲🇱" },
  { code: "MT", name: "مالطا", dial: "356", flag: "🇲🇹" },
  { code: "MH", name: "جزر مارشال", dial: "692", flag: "🇲🇭" },
  { code: "MU", name: "موريشيوس", dial: "230", flag: "🇲🇺" },
  { code: "MX", name: "المكسيك", dial: "52", flag: "🇲🇽" },
  { code: "FM", name: "ميكرونيزيا", dial: "691", flag: "🇫🇲" },
  { code: "MD", name: "مولدوفا", dial: "373", flag: "🇲🇩" },
  { code: "MC", name: "موناكو", dial: "377", flag: "🇲🇨" },
  { code: "MN", name: "منغوليا", dial: "976", flag: "🇲🇳" },
  { code: "ME", name: "الجبل الأسود", dial: "382", flag: "🇲🇪" },
  { code: "MZ", name: "موزمبيق", dial: "258", flag: "🇲🇿" },
  { code: "MM", name: "ميانمار", dial: "95", flag: "🇲🇲" },
  { code: "NA", name: "ناميبيا", dial: "264", flag: "🇳🇦" },
  { code: "NR", name: "ناورو", dial: "674", flag: "🇳🇷" },
  { code: "NP", name: "نيبال", dial: "977", flag: "🇳🇵" },
  { code: "NL", name: "هولندا", dial: "31", flag: "🇳🇱" },
  { code: "NZ", name: "نيوزيلندا", dial: "64", flag: "🇳🇿" },
  { code: "NI", name: "نيكاراغوا", dial: "505", flag: "🇳🇮" },
  { code: "NE", name: "النيجر", dial: "227", flag: "🇳🇪" },
  { code: "NG", name: "نيجيريا", dial: "234", flag: "🇳🇬" },
  { code: "KP", name: "كوريا الشمالية", dial: "850", flag: "🇰🇵" },
  { code: "MK", name: "مقدونيا الشمالية", dial: "389", flag: "🇲🇰" },
  { code: "NO", name: "النرويج", dial: "47", flag: "🇳🇴" },
  { code: "PK", name: "باكستان", dial: "92", flag: "🇵🇰" },
  { code: "PW", name: "بالاو", dial: "680", flag: "🇵🇼" },
  { code: "PA", name: "بنما", dial: "507", flag: "🇵🇦" },
  { code: "PG", name: "بابوا غينيا الجديدة", dial: "675", flag: "🇵🇬" },
  { code: "PY", name: "باراغواي", dial: "595", flag: "🇵🇾" },
  { code: "PE", name: "بيرو", dial: "51", flag: "🇵🇪" },
  { code: "PH", name: "الفلبين", dial: "63", flag: "🇵🇭" },
  { code: "PL", name: "بولندا", dial: "48", flag: "🇵🇱" },
  { code: "PT", name: "البرتغال", dial: "351", flag: "🇵🇹" },
  { code: "PR", name: "بورتوريكو", dial: "1787", flag: "🇵🇷" },
  { code: "RO", name: "رومانيا", dial: "40", flag: "🇷🇴" },
  { code: "RU", name: "روسيا", dial: "7", flag: "🇷🇺" },
  { code: "RW", name: "رواندا", dial: "250", flag: "🇷🇼" },
  { code: "KN", name: "سانت كيتس ونيفيس", dial: "1869", flag: "🇰🇳" },
  { code: "LC", name: "سانت لوسيا", dial: "1758", flag: "🇱🇨" },
  { code: "VC", name: "سانت فينسنت", dial: "1784", flag: "🇻🇨" },
  { code: "WS", name: "ساموا", dial: "685", flag: "🇼🇸" },
  { code: "SM", name: "سان مارينو", dial: "378", flag: "🇸🇲" },
  { code: "ST", name: "ساو تومي وبرينسيبي", dial: "239", flag: "🇸🇹" },
  { code: "SN", name: "السنغال", dial: "221", flag: "🇸🇳" },
  { code: "RS", name: "صربيا", dial: "381", flag: "🇷🇸" },
  { code: "SC", name: "سيشل", dial: "248", flag: "🇸🇨" },
  { code: "SL", name: "سيراليون", dial: "232", flag: "🇸🇱" },
  { code: "SG", name: "سنغافورة", dial: "65", flag: "🇸🇬" },
  { code: "SK", name: "سلوفاكيا", dial: "421", flag: "🇸🇰" },
  { code: "SI", name: "سلوفينيا", dial: "386", flag: "🇸🇮" },
  { code: "SB", name: "جزر سولومون", dial: "677", flag: "🇸🇧" },
  { code: "ZA", name: "جنوب أفريقيا", dial: "27", flag: "🇿🇦" },
  { code: "KR", name: "كوريا الجنوبية", dial: "82", flag: "🇰🇷" },
  { code: "SS", name: "جنوب السودان", dial: "211", flag: "🇸🇸" },
  { code: "ES", name: "إسبانيا", dial: "34", flag: "🇪🇸" },
  { code: "LK", name: "سريلانكا", dial: "94", flag: "🇱🇰" },
  { code: "SR", name: "سورينام", dial: "597", flag: "🇸🇷" },
  { code: "SE", name: "السويد", dial: "46", flag: "🇸🇪" },
  { code: "CH", name: "سويسرا", dial: "41", flag: "🇨🇭" },
  { code: "TW", name: "تايوان", dial: "886", flag: "🇹🇼" },
  { code: "TJ", name: "طاجيكستان", dial: "992", flag: "🇹🇯" },
  { code: "TZ", name: "تنزانيا", dial: "255", flag: "🇹🇿" },
  { code: "TH", name: "تايلاند", dial: "66", flag: "🇹🇭" },
  { code: "TL", name: "تيمور الشرقية", dial: "670", flag: "🇹🇱" },
  { code: "TG", name: "توغو", dial: "228", flag: "🇹🇬" },
  { code: "TO", name: "تونغا", dial: "676", flag: "🇹🇴" },
  { code: "TT", name: "ترينيداد وتوباغو", dial: "1868", flag: "🇹🇹" },
  { code: "TM", name: "تركمانستان", dial: "993", flag: "🇹🇲" },
  { code: "TV", name: "توفالو", dial: "688", flag: "🇹🇻" },
  { code: "UG", name: "أوغندا", dial: "256", flag: "🇺🇬" },
  { code: "UA", name: "أوكرانيا", dial: "380", flag: "🇺🇦" },
  { code: "GB", name: "بريطانيا", dial: "44", flag: "🇬🇧" },
  { code: "US", name: "الولايات المتحدة", dial: "1", flag: "🇺🇸" },
  { code: "UY", name: "أوروغواي", dial: "598", flag: "🇺🇾" },
  { code: "UZ", name: "أوزبكستان", dial: "998", flag: "🇺🇿" },
  { code: "VU", name: "فانواتو", dial: "678", flag: "🇻🇺" },
  { code: "VA", name: "الفاتيكان", dial: "379", flag: "🇻🇦" },
  { code: "VE", name: "فنزويلا", dial: "58", flag: "🇻🇪" },
  { code: "VN", name: "فيتنام", dial: "84", flag: "🇻🇳" },
  { code: "ZM", name: "زامبيا", dial: "260", flag: "🇿🇲" },
  { code: "ZW", name: "زيمبابوي", dial: "263", flag: "🇿🇼" },
];

export const DEFAULT_COUNTRY_CODE = "EG";

export function findCountry(code: string): Country | undefined {
  return COUNTRIES.find((c) => c.code === code);
}

export function findCountryByName(name: string): Country | undefined {
  return COUNTRIES.find((c) => c.name === name);
}

export function searchCountries(term: string): Country[] {
  const q = term.trim().toLowerCase();
  if (!q) return COUNTRIES;
  return COUNTRIES.filter(
    (c) =>
      c.name.includes(q) ||
      c.name.toLowerCase().includes(q) ||
      c.code.toLowerCase().includes(q) ||
      c.dial.includes(q.replace(/^\+/, "")),
  );
}

export const COUNTRY_NAMES = COUNTRIES.map((c) => c.name);
