/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedAchievementsRouteImport } from './routes/_authenticated/achievements'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminToolsRouteImport } from './routes/_authenticated/admin-tools'
import { Route as AuthenticatedBoxesRouteImport } from './routes/_authenticated/boxes'
import { Route as AuthenticatedCrownRouteImport } from './routes/_authenticated/crown'
import { Route as AuthenticatedCupRouteImport } from './routes/_authenticated/cup'
import { Route as AuthenticatedFriendsRouteImport } from './routes/_authenticated/friends'
import { Route as AuthenticatedGamesRouteImport } from './routes/_authenticated/games'
import { Route as AuthenticatedGiftLogRouteImport } from './routes/_authenticated/gift-log'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated/help'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedMarketRouteImport } from './routes/_authenticated/market'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthenticatedMyStatsRouteImport } from './routes/_authenticated/my-stats'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedOwnerStatsRouteImport } from './routes/_authenticated/owner-stats'
import { Route as AuthenticatedProfilePlusRouteImport } from './routes/_authenticated/profile-plus'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedStoreRouteImport } from './routes/_authenticated/store'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedEventsEventIdRouteImport } from './routes/_authenticated/events.$eventId'
import { Route as AuthenticatedFamiliesIndexRouteImport } from './routes/_authenticated/families.index'
import { Route as AuthenticatedFamiliesFamilyIdRouteImport } from './routes/_authenticated/families.$familyId'
import { Route as AuthenticatedMessagesIndexRouteImport } from './routes/_authenticated/messages.index'
import { Route as AuthenticatedMessagesUserIdRouteImport } from './routes/_authenticated/messages.$userId'
import { Route as AuthenticatedRoomsIndexRouteImport } from './routes/_authenticated/rooms.index'
import { Route as AuthenticatedRoomsRoomIdRouteImport } from './routes/_authenticated/rooms.$roomId'
import { Route as AuthenticatedUPublicIdRouteImport } from './routes/_authenticated/u.$publicId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAchievementsRoute =
  AuthenticatedAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminToolsRoute = AuthenticatedAdminToolsRouteImport.update({
  id: '/admin-tools',
  path: '/admin-tools',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBoxesRoute = AuthenticatedBoxesRouteImport.update({
  id: '/boxes',
  path: '/boxes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrownRoute = AuthenticatedCrownRouteImport.update({
  id: '/crown',
  path: '/crown',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCupRoute = AuthenticatedCupRouteImport.update({
  id: '/cup',
  path: '/cup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFriendsRoute = AuthenticatedFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGamesRoute = AuthenticatedGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGiftLogRoute = AuthenticatedGiftLogRouteImport.update({
  id: '/gift-log',
  path: '/gift-log',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketRoute = AuthenticatedMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyStatsRoute = AuthenticatedMyStatsRouteImport.update({
  id: '/my-stats',
  path: '/my-stats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerStatsRoute = AuthenticatedOwnerStatsRouteImport.update({
  id: '/owner-stats',
  path: '/owner-stats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfilePlusRoute =
  AuthenticatedProfilePlusRouteImport.update({
    id: '/profile-plus',
    path: '/profile-plus',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStoreRoute = AuthenticatedStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventsEventIdRoute =
  AuthenticatedEventsEventIdRouteImport.update({
    id: '/events/$eventId',
    path: '/events/$eventId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFamiliesIndexRoute =
  AuthenticatedFamiliesIndexRouteImport.update({
    id: '/families/',
    path: '/families/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFamiliesFamilyIdRoute =
  AuthenticatedFamiliesFamilyIdRouteImport.update({
    id: '/families/$familyId',
    path: '/families/$familyId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesIndexRoute =
  AuthenticatedMessagesIndexRouteImport.update({
    id: '/messages/',
    path: '/messages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesUserIdRoute =
  AuthenticatedMessagesUserIdRouteImport.update({
    id: '/messages/$userId',
    path: '/messages/$userId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRoomsIndexRoute = AuthenticatedRoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoomsRoomIdRoute =
  AuthenticatedRoomsRoomIdRouteImport.update({
    id: '/rooms/$roomId',
    path: '/rooms/$roomId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUPublicIdRoute = AuthenticatedUPublicIdRouteImport.update({
  id: '/u/$publicId',
  path: '/u/$publicId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin-tools': typeof AuthenticatedAdminToolsRoute
  '/boxes': typeof AuthenticatedBoxesRoute
  '/crown': typeof AuthenticatedCrownRoute
  '/cup': typeof AuthenticatedCupRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/games': typeof AuthenticatedGamesRoute
  '/gift-log': typeof AuthenticatedGiftLogRoute
  '/help': typeof AuthenticatedHelpRoute
  '/home': typeof AuthenticatedHomeRoute
  '/market': typeof AuthenticatedMarketRoute
  '/me': typeof AuthenticatedMeRoute
  '/my-stats': typeof AuthenticatedMyStatsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/owner-stats': typeof AuthenticatedOwnerStatsRoute
  '/profile-plus': typeof AuthenticatedProfilePlusRoute
  '/search': typeof AuthenticatedSearchRoute
  '/store': typeof AuthenticatedStoreRoute
  '/support': typeof AuthenticatedSupportRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/families/$familyId': typeof AuthenticatedFamiliesFamilyIdRoute
  '/messages/$userId': typeof AuthenticatedMessagesUserIdRoute
  '/rooms/$roomId': typeof AuthenticatedRoomsRoomIdRoute
  '/u/$publicId': typeof AuthenticatedUPublicIdRoute
  '/families/': typeof AuthenticatedFamiliesIndexRoute
  '/messages/': typeof AuthenticatedMessagesIndexRoute
  '/rooms/': typeof AuthenticatedRoomsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin-tools': typeof AuthenticatedAdminToolsRoute
  '/boxes': typeof AuthenticatedBoxesRoute
  '/crown': typeof AuthenticatedCrownRoute
  '/cup': typeof AuthenticatedCupRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/games': typeof AuthenticatedGamesRoute
  '/gift-log': typeof AuthenticatedGiftLogRoute
  '/help': typeof AuthenticatedHelpRoute
  '/home': typeof AuthenticatedHomeRoute
  '/market': typeof AuthenticatedMarketRoute
  '/me': typeof AuthenticatedMeRoute
  '/my-stats': typeof AuthenticatedMyStatsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/owner-stats': typeof AuthenticatedOwnerStatsRoute
  '/profile-plus': typeof AuthenticatedProfilePlusRoute
  '/search': typeof AuthenticatedSearchRoute
  '/store': typeof AuthenticatedStoreRoute
  '/support': typeof AuthenticatedSupportRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/families/$familyId': typeof AuthenticatedFamiliesFamilyIdRoute
  '/messages/$userId': typeof AuthenticatedMessagesUserIdRoute
  '/rooms/$roomId': typeof AuthenticatedRoomsRoomIdRoute
  '/u/$publicId': typeof AuthenticatedUPublicIdRoute
  '/families': typeof AuthenticatedFamiliesIndexRoute
  '/messages': typeof AuthenticatedMessagesIndexRoute
  '/rooms': typeof AuthenticatedRoomsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/achievements': typeof AuthenticatedAchievementsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/admin-tools': typeof AuthenticatedAdminToolsRoute
  '/_authenticated/boxes': typeof AuthenticatedBoxesRoute
  '/_authenticated/crown': typeof AuthenticatedCrownRoute
  '/_authenticated/cup': typeof AuthenticatedCupRoute
  '/_authenticated/friends': typeof AuthenticatedFriendsRoute
  '/_authenticated/games': typeof AuthenticatedGamesRoute
  '/_authenticated/gift-log': typeof AuthenticatedGiftLogRoute
  '/_authenticated/help': typeof AuthenticatedHelpRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/market': typeof AuthenticatedMarketRoute
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/_authenticated/my-stats': typeof AuthenticatedMyStatsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/owner-stats': typeof AuthenticatedOwnerStatsRoute
  '/_authenticated/profile-plus': typeof AuthenticatedProfilePlusRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/store': typeof AuthenticatedStoreRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/_authenticated/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/_authenticated/families/$familyId': typeof AuthenticatedFamiliesFamilyIdRoute
  '/_authenticated/messages/$userId': typeof AuthenticatedMessagesUserIdRoute
  '/_authenticated/rooms/$roomId': typeof AuthenticatedRoomsRoomIdRoute
  '/_authenticated/u/$publicId': typeof AuthenticatedUPublicIdRoute
  '/_authenticated/families/': typeof AuthenticatedFamiliesIndexRoute
  '/_authenticated/messages/': typeof AuthenticatedMessagesIndexRoute
  '/_authenticated/rooms/': typeof AuthenticatedRoomsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/admin'
    | '/admin-tools'
    | '/boxes'
    | '/crown'
    | '/cup'
    | '/friends'
    | '/games'
    | '/gift-log'
    | '/help'
    | '/home'
    | '/market'
    | '/me'
    | '/my-stats'
    | '/notifications'
    | '/owner-stats'
    | '/profile-plus'
    | '/search'
    | '/store'
    | '/support'
    | '/tasks'
    | '/wallet'
    | '/events/$eventId'
    | '/families/$familyId'
    | '/messages/$userId'
    | '/rooms/$roomId'
    | '/u/$publicId'
    | '/families/'
    | '/messages/'
    | '/rooms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/admin'
    | '/admin-tools'
    | '/boxes'
    | '/crown'
    | '/cup'
    | '/friends'
    | '/games'
    | '/gift-log'
    | '/help'
    | '/home'
    | '/market'
    | '/me'
    | '/my-stats'
    | '/notifications'
    | '/owner-stats'
    | '/profile-plus'
    | '/search'
    | '/store'
    | '/support'
    | '/tasks'
    | '/wallet'
    | '/events/$eventId'
    | '/families/$familyId'
    | '/messages/$userId'
    | '/rooms/$roomId'
    | '/u/$publicId'
    | '/families'
    | '/messages'
    | '/rooms'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/achievements'
    | '/_authenticated/admin'
    | '/_authenticated/admin-tools'
    | '/_authenticated/boxes'
    | '/_authenticated/crown'
    | '/_authenticated/cup'
    | '/_authenticated/friends'
    | '/_authenticated/games'
    | '/_authenticated/gift-log'
    | '/_authenticated/help'
    | '/_authenticated/home'
    | '/_authenticated/market'
    | '/_authenticated/me'
    | '/_authenticated/my-stats'
    | '/_authenticated/notifications'
    | '/_authenticated/owner-stats'
    | '/_authenticated/profile-plus'
    | '/_authenticated/search'
    | '/_authenticated/store'
    | '/_authenticated/support'
    | '/_authenticated/tasks'
    | '/_authenticated/wallet'
    | '/_authenticated/events/$eventId'
    | '/_authenticated/families/$familyId'
    | '/_authenticated/messages/$userId'
    | '/_authenticated/rooms/$roomId'
    | '/_authenticated/u/$publicId'
    | '/_authenticated/families/'
    | '/_authenticated/messages/'
    | '/_authenticated/rooms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/achievements': {
      id: '/_authenticated/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AuthenticatedAchievementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-tools': {
      id: '/_authenticated/admin-tools'
      path: '/admin-tools'
      fullPath: '/admin-tools'
      preLoaderRoute: typeof AuthenticatedAdminToolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/boxes': {
      id: '/_authenticated/boxes'
      path: '/boxes'
      fullPath: '/boxes'
      preLoaderRoute: typeof AuthenticatedBoxesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crown': {
      id: '/_authenticated/crown'
      path: '/crown'
      fullPath: '/crown'
      preLoaderRoute: typeof AuthenticatedCrownRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cup': {
      id: '/_authenticated/cup'
      path: '/cup'
      fullPath: '/cup'
      preLoaderRoute: typeof AuthenticatedCupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/friends': {
      id: '/_authenticated/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AuthenticatedFriendsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/games': {
      id: '/_authenticated/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof AuthenticatedGamesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gift-log': {
      id: '/_authenticated/gift-log'
      path: '/gift-log'
      fullPath: '/gift-log'
      preLoaderRoute: typeof AuthenticatedGiftLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/market': {
      id: '/_authenticated/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof AuthenticatedMarketRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-stats': {
      id: '/_authenticated/my-stats'
      path: '/my-stats'
      fullPath: '/my-stats'
      preLoaderRoute: typeof AuthenticatedMyStatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner-stats': {
      id: '/_authenticated/owner-stats'
      path: '/owner-stats'
      fullPath: '/owner-stats'
      preLoaderRoute: typeof AuthenticatedOwnerStatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile-plus': {
      id: '/_authenticated/profile-plus'
      path: '/profile-plus'
      fullPath: '/profile-plus'
      preLoaderRoute: typeof AuthenticatedProfilePlusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/store': {
      id: '/_authenticated/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof AuthenticatedStoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/$eventId': {
      id: '/_authenticated/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AuthenticatedEventsEventIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/families/': {
      id: '/_authenticated/families/'
      path: '/families'
      fullPath: '/families/'
      preLoaderRoute: typeof AuthenticatedFamiliesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/families/$familyId': {
      id: '/_authenticated/families/$familyId'
      path: '/families/$familyId'
      fullPath: '/families/$familyId'
      preLoaderRoute: typeof AuthenticatedFamiliesFamilyIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/': {
      id: '/_authenticated/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof AuthenticatedMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/$userId': {
      id: '/_authenticated/messages/$userId'
      path: '/messages/$userId'
      fullPath: '/messages/$userId'
      preLoaderRoute: typeof AuthenticatedMessagesUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rooms/': {
      id: '/_authenticated/rooms/'
      path: '/rooms'
      fullPath: '/rooms/'
      preLoaderRoute: typeof AuthenticatedRoomsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rooms/$roomId': {
      id: '/_authenticated/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof AuthenticatedRoomsRoomIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/u/$publicId': {
      id: '/_authenticated/u/$publicId'
      path: '/u/$publicId'
      fullPath: '/u/$publicId'
      preLoaderRoute: typeof AuthenticatedUPublicIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAchievementsRoute: typeof AuthenticatedAchievementsRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAdminToolsRoute: typeof AuthenticatedAdminToolsRoute
  AuthenticatedBoxesRoute: typeof AuthenticatedBoxesRoute
  AuthenticatedCrownRoute: typeof AuthenticatedCrownRoute
  AuthenticatedCupRoute: typeof AuthenticatedCupRoute
  AuthenticatedFriendsRoute: typeof AuthenticatedFriendsRoute
  AuthenticatedGamesRoute: typeof AuthenticatedGamesRoute
  AuthenticatedGiftLogRoute: typeof AuthenticatedGiftLogRoute
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedMarketRoute: typeof AuthenticatedMarketRoute
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedMyStatsRoute: typeof AuthenticatedMyStatsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOwnerStatsRoute: typeof AuthenticatedOwnerStatsRoute
  AuthenticatedProfilePlusRoute: typeof AuthenticatedProfilePlusRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedStoreRoute: typeof AuthenticatedStoreRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedEventsEventIdRoute: typeof AuthenticatedEventsEventIdRoute
  AuthenticatedFamiliesFamilyIdRoute: typeof AuthenticatedFamiliesFamilyIdRoute
  AuthenticatedMessagesUserIdRoute: typeof AuthenticatedMessagesUserIdRoute
  AuthenticatedRoomsRoomIdRoute: typeof AuthenticatedRoomsRoomIdRoute
  AuthenticatedUPublicIdRoute: typeof AuthenticatedUPublicIdRoute
  AuthenticatedFamiliesIndexRoute: typeof AuthenticatedFamiliesIndexRoute
  AuthenticatedMessagesIndexRoute: typeof AuthenticatedMessagesIndexRoute
  AuthenticatedRoomsIndexRoute: typeof AuthenticatedRoomsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAchievementsRoute: AuthenticatedAchievementsRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAdminToolsRoute: AuthenticatedAdminToolsRoute,
  AuthenticatedBoxesRoute: AuthenticatedBoxesRoute,
  AuthenticatedCrownRoute: AuthenticatedCrownRoute,
  AuthenticatedCupRoute: AuthenticatedCupRoute,
  AuthenticatedFriendsRoute: AuthenticatedFriendsRoute,
  AuthenticatedGamesRoute: AuthenticatedGamesRoute,
  AuthenticatedGiftLogRoute: AuthenticatedGiftLogRoute,
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedMarketRoute: AuthenticatedMarketRoute,
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedMyStatsRoute: AuthenticatedMyStatsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOwnerStatsRoute: AuthenticatedOwnerStatsRoute,
  AuthenticatedProfilePlusRoute: AuthenticatedProfilePlusRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedStoreRoute: AuthenticatedStoreRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedEventsEventIdRoute: AuthenticatedEventsEventIdRoute,
  AuthenticatedFamiliesFamilyIdRoute: AuthenticatedFamiliesFamilyIdRoute,
  AuthenticatedMessagesUserIdRoute: AuthenticatedMessagesUserIdRoute,
  AuthenticatedRoomsRoomIdRoute: AuthenticatedRoomsRoomIdRoute,
  AuthenticatedUPublicIdRoute: AuthenticatedUPublicIdRoute,
  AuthenticatedFamiliesIndexRoute: AuthenticatedFamiliesIndexRoute,
  AuthenticatedMessagesIndexRoute: AuthenticatedMessagesIndexRoute,
  AuthenticatedRoomsIndexRoute: AuthenticatedRoomsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
