/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedGamesRouteImport } from './routes/_authenticated/games'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedRoomsRouteImport } from './routes/_authenticated/rooms'
import { Route as AuthenticatedStoreRouteImport } from './routes/_authenticated/store'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedMessagesUserIdRouteImport } from './routes/_authenticated/messages.$userId'
import { Route as AuthenticatedRoomsRoomIdRouteImport } from './routes/_authenticated/rooms.$roomId'
import { Route as AuthenticatedUPublicIdRouteImport } from './routes/_authenticated/u.$publicId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGamesRoute = AuthenticatedGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoomsRoute = AuthenticatedRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStoreRoute = AuthenticatedStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesUserIdRoute =
  AuthenticatedMessagesUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedMessagesRoute,
  } as any)
const AuthenticatedRoomsRoomIdRoute =
  AuthenticatedRoomsRoomIdRouteImport.update({
    id: '/$roomId',
    path: '/$roomId',
    getParentRoute: () => AuthenticatedRoomsRoute,
  } as any)
const AuthenticatedUPublicIdRoute = AuthenticatedUPublicIdRouteImport.update({
  id: '/u/$publicId',
  path: '/u/$publicId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/games': typeof AuthenticatedGamesRoute
  '/home': typeof AuthenticatedHomeRoute
  '/me': typeof AuthenticatedMeRoute
  '/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/rooms': typeof AuthenticatedRoomsRouteWithChildren
  '/store': typeof AuthenticatedStoreRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/messages/$userId': typeof AuthenticatedMessagesUserIdRoute
  '/rooms/$roomId': typeof AuthenticatedRoomsRoomIdRoute
  '/u/$publicId': typeof AuthenticatedUPublicIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/games': typeof AuthenticatedGamesRoute
  '/home': typeof AuthenticatedHomeRoute
  '/me': typeof AuthenticatedMeRoute
  '/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/rooms': typeof AuthenticatedRoomsRouteWithChildren
  '/store': typeof AuthenticatedStoreRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/messages/$userId': typeof AuthenticatedMessagesUserIdRoute
  '/rooms/$roomId': typeof AuthenticatedRoomsRoomIdRoute
  '/u/$publicId': typeof AuthenticatedUPublicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/games': typeof AuthenticatedGamesRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/_authenticated/rooms': typeof AuthenticatedRoomsRouteWithChildren
  '/_authenticated/store': typeof AuthenticatedStoreRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/_authenticated/messages/$userId': typeof AuthenticatedMessagesUserIdRoute
  '/_authenticated/rooms/$roomId': typeof AuthenticatedRoomsRoomIdRoute
  '/_authenticated/u/$publicId': typeof AuthenticatedUPublicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/games'
    | '/home'
    | '/me'
    | '/messages'
    | '/rooms'
    | '/store'
    | '/wallet'
    | '/messages/$userId'
    | '/rooms/$roomId'
    | '/u/$publicId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/games'
    | '/home'
    | '/me'
    | '/messages'
    | '/rooms'
    | '/store'
    | '/wallet'
    | '/messages/$userId'
    | '/rooms/$roomId'
    | '/u/$publicId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/admin'
    | '/_authenticated/games'
    | '/_authenticated/home'
    | '/_authenticated/me'
    | '/_authenticated/messages'
    | '/_authenticated/rooms'
    | '/_authenticated/store'
    | '/_authenticated/wallet'
    | '/_authenticated/messages/$userId'
    | '/_authenticated/rooms/$roomId'
    | '/_authenticated/u/$publicId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/games': {
      id: '/_authenticated/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof AuthenticatedGamesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rooms': {
      id: '/_authenticated/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AuthenticatedRoomsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/store': {
      id: '/_authenticated/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof AuthenticatedStoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/$userId': {
      id: '/_authenticated/messages/$userId'
      path: '/$userId'
      fullPath: '/messages/$userId'
      preLoaderRoute: typeof AuthenticatedMessagesUserIdRouteImport
      parentRoute: typeof AuthenticatedMessagesRoute
    }
    '/_authenticated/rooms/$roomId': {
      id: '/_authenticated/rooms/$roomId'
      path: '/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof AuthenticatedRoomsRoomIdRouteImport
      parentRoute: typeof AuthenticatedRoomsRoute
    }
    '/_authenticated/u/$publicId': {
      id: '/_authenticated/u/$publicId'
      path: '/u/$publicId'
      fullPath: '/u/$publicId'
      preLoaderRoute: typeof AuthenticatedUPublicIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedMessagesRouteChildren {
  AuthenticatedMessagesUserIdRoute: typeof AuthenticatedMessagesUserIdRoute
}

const AuthenticatedMessagesRouteChildren: AuthenticatedMessagesRouteChildren = {
  AuthenticatedMessagesUserIdRoute: AuthenticatedMessagesUserIdRoute,
}

const AuthenticatedMessagesRouteWithChildren =
  AuthenticatedMessagesRoute._addFileChildren(
    AuthenticatedMessagesRouteChildren,
  )

interface AuthenticatedRoomsRouteChildren {
  AuthenticatedRoomsRoomIdRoute: typeof AuthenticatedRoomsRoomIdRoute
}

const AuthenticatedRoomsRouteChildren: AuthenticatedRoomsRouteChildren = {
  AuthenticatedRoomsRoomIdRoute: AuthenticatedRoomsRoomIdRoute,
}

const AuthenticatedRoomsRouteWithChildren =
  AuthenticatedRoomsRoute._addFileChildren(AuthenticatedRoomsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedGamesRoute: typeof AuthenticatedGamesRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRouteWithChildren
  AuthenticatedRoomsRoute: typeof AuthenticatedRoomsRouteWithChildren
  AuthenticatedStoreRoute: typeof AuthenticatedStoreRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedUPublicIdRoute: typeof AuthenticatedUPublicIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedGamesRoute: AuthenticatedGamesRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRouteWithChildren,
  AuthenticatedRoomsRoute: AuthenticatedRoomsRouteWithChildren,
  AuthenticatedStoreRoute: AuthenticatedStoreRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedUPublicIdRoute: AuthenticatedUPublicIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
