CREATE TABLE public.wheel_rounds (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  round_no bigint GENERATED BY DEFAULT AS IDENTITY,
  status text NOT NULL DEFAULT 'betting',
  slots jsonb NOT NULL,
  winning_key text,
  started_at timestamptz NOT NULL DEFAULT now(),
  ends_at timestamptz NOT NULL,
  settled_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.wheel_bets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  round_id uuid NOT NULL REFERENCES public.wheel_rounds(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  room_id uuid REFERENCES public.rooms(id) ON DELETE SET NULL,
  slot_key text NOT NULL,
  amount bigint NOT NULL,
  payout bigint NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX wheel_bets_round_idx ON public.wheel_bets (round_id);
CREATE INDEX wheel_bets_user_idx ON public.wheel_bets (user_id, created_at DESC);
CREATE INDEX wheel_rounds_status_idx ON public.wheel_rounds (status, created_at DESC);

GRANT SELECT ON public.wheel_rounds TO authenticated;
GRANT ALL ON public.wheel_rounds TO service_role;
GRANT SELECT ON public.wheel_bets TO authenticated;
GRANT ALL ON public.wheel_bets TO service_role;

ALTER TABLE public.wheel_rounds ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wheel_bets ENABLE ROW LEVEL SECURITY;

CREATE POLICY "wheel_rounds_read" ON public.wheel_rounds FOR SELECT TO authenticated USING (true);
CREATE POLICY "wheel_bets_read" ON public.wheel_bets FOR SELECT TO authenticated USING (true);

ALTER PUBLICATION supabase_realtime ADD TABLE public.wheel_rounds;
ALTER PUBLICATION supabase_realtime ADD TABLE public.wheel_bets;

INSERT INTO public.app_settings (key, value) VALUES ('wheel', jsonb_build_object(
  'enabled', true,
  'duration_seconds', 10,
  'result_seconds', 3,
  'min_bet', 100,
  'max_bet', 100000,
  'slots', jsonb_build_array(
    jsonb_build_object('key','grapes','label','عنب','emoji','🍇','multiplier',5,'weight',26),
    jsonb_build_object('key','watermelon','label','بطيخ','emoji','🍉','multiplier',5,'weight',26),
    jsonb_build_object('key','apple','label','تفاح','emoji','🍎','multiplier',5,'weight',26),
    jsonb_build_object('key','lemon','label','ليمون','emoji','🍋','multiplier',15,'weight',9),
    jsonb_build_object('key','cherry','label','كرز','emoji','🍒','multiplier',20,'weight',6),
    jsonb_build_object('key','strawberry','label','فراولة','emoji','🍓','multiplier',25,'weight',5),
    jsonb_build_object('key','crown','label','التاج','emoji','👑','multiplier',90,'weight',2)
  )
)) ON CONFLICT (key) DO NOTHING;

CREATE OR REPLACE FUNCTION public.wheel_settings()
RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$ SELECT coalesce((SELECT value FROM app_settings WHERE key = 'wheel'), '{}'::jsonb) $$;

REVOKE ALL ON FUNCTION public.wheel_settings() FROM anon, authenticated;

CREATE OR REPLACE FUNCTION public.wheel_settle(_round_id uuid)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  r public.wheel_rounds;
  total numeric := 0;
  ticket numeric;
  slot jsonb;
  win_key text;
  b record;
  mult numeric;
  bal bigint;
  prize bigint;
BEGIN
  SELECT * INTO r FROM public.wheel_rounds WHERE id = _round_id FOR UPDATE;
  IF r.id IS NULL OR r.status = 'finished' THEN RETURN; END IF;

  FOR slot IN SELECT * FROM jsonb_array_elements(r.slots) LOOP
    total := total + coalesce((slot->>'weight')::numeric, 1);
  END LOOP;
  ticket := random() * total;
  FOR slot IN SELECT * FROM jsonb_array_elements(r.slots) LOOP
    ticket := ticket - coalesce((slot->>'weight')::numeric, 1);
    IF win_key IS NULL AND ticket <= 0 THEN win_key := slot->>'key'; END IF;
  END LOOP;
  IF win_key IS NULL THEN win_key := (r.slots->0->>'key'); END IF;

  SELECT coalesce((s->>'multiplier')::numeric, 0) INTO mult
  FROM jsonb_array_elements(r.slots) s WHERE s->>'key' = win_key;

  FOR b IN SELECT * FROM public.wheel_bets WHERE round_id = r.id AND slot_key = win_key LOOP
    prize := floor(b.amount * coalesce(mult, 0))::bigint;
    IF prize > 0 THEN
      SELECT coins INTO bal FROM public.coin_wallets WHERE user_id = b.user_id FOR UPDATE;
      IF bal IS NOT NULL THEN
        UPDATE public.coin_wallets SET coins = bal + prize, updated_at = now() WHERE user_id = b.user_id;
        INSERT INTO public.coin_transactions (user_id, kind, amount, balance_before, balance_after, reference)
          VALUES (b.user_id, 'game', prize, bal, bal + prize, 'wheel:win:' || win_key);
        UPDATE public.wheel_bets SET payout = prize WHERE id = b.id;
      END IF;
    END IF;
  END LOOP;

  UPDATE public.wheel_rounds
    SET status = 'finished', winning_key = win_key, settled_at = now()
    WHERE id = r.id;
END $$;

REVOKE ALL ON FUNCTION public.wheel_settle(uuid) FROM anon, authenticated;

CREATE OR REPLACE FUNCTION public.wheel_tick()
RETURNS public.wheel_rounds LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  s jsonb := public.wheel_settings();
  r public.wheel_rounds;
  dur integer := greatest(coalesce((s->>'duration_seconds')::integer, 10), 5);
  gap integer := greatest(coalesce((s->>'result_seconds')::integer, 3), 1);
BEGIN
  IF coalesce((s->>'enabled')::boolean, true) = false THEN
    RAISE EXCEPTION 'لعبة العجلة موقوفة حاليًا';
  END IF;

  SELECT * INTO r FROM public.wheel_rounds WHERE status = 'betting' ORDER BY created_at DESC LIMIT 1;
  IF r.id IS NOT NULL AND r.ends_at <= now() THEN
    PERFORM public.wheel_settle(r.id);
    SELECT * INTO r FROM public.wheel_rounds WHERE id = r.id;
  END IF;

  IF r.id IS NULL OR r.status = 'finished' THEN
    SELECT * INTO r FROM public.wheel_rounds ORDER BY created_at DESC LIMIT 1;
    IF r.id IS NULL OR (r.status = 'finished' AND coalesce(r.settled_at, r.ends_at) + make_interval(secs => gap) <= now()) THEN
      INSERT INTO public.wheel_rounds (slots, ends_at)
        VALUES (coalesce(s->'slots', '[]'::jsonb), now() + make_interval(secs => dur))
        RETURNING * INTO r;
    END IF;
  END IF;
  RETURN r;
END $$;

CREATE OR REPLACE FUNCTION public.wheel_bet(_slot_key text, _amount bigint, _room_id uuid DEFAULT NULL)
RETURNS public.wheel_bets LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  uid uuid := auth.uid();
  s jsonb := public.wheel_settings();
  r public.wheel_rounds;
  bal bigint;
  b public.wheel_bets;
  min_bet bigint := coalesce((s->>'min_bet')::bigint, 100);
  max_bet bigint := coalesce((s->>'max_bet')::bigint, 100000);
BEGIN
  IF uid IS NULL THEN RAISE EXCEPTION 'يجب تسجيل الدخول'; END IF;
  IF coalesce((s->>'enabled')::boolean, true) = false THEN RAISE EXCEPTION 'لعبة العجلة موقوفة حاليًا'; END IF;
  IF _amount < min_bet OR _amount > max_bet THEN
    RAISE EXCEPTION 'الرهان يجب أن يكون بين % و % كوينز', min_bet, max_bet;
  END IF;
  IF EXISTS (SELECT 1 FROM public.profiles WHERE id = uid AND is_suspended) THEN
    RAISE EXCEPTION 'حسابك موقوف';
  END IF;

  SELECT * INTO r FROM public.wheel_rounds WHERE status = 'betting' AND ends_at > now()
    ORDER BY created_at DESC LIMIT 1 FOR UPDATE;
  IF r.id IS NULL THEN RAISE EXCEPTION 'انتهى وقت المراهنة، انتظر الجولة التالية'; END IF;
  IF NOT EXISTS (SELECT 1 FROM jsonb_array_elements(r.slots) x WHERE x->>'key' = _slot_key) THEN
    RAISE EXCEPTION 'خانة غير صالحة';
  END IF;

  SELECT coins INTO bal FROM public.coin_wallets WHERE user_id = uid FOR UPDATE;
  IF bal IS NULL THEN RAISE EXCEPTION 'لا توجد محفظة'; END IF;
  IF bal < _amount THEN RAISE EXCEPTION 'رصيدك غير كافٍ'; END IF;

  UPDATE public.coin_wallets SET coins = bal - _amount, updated_at = now() WHERE user_id = uid;
  INSERT INTO public.coin_transactions (user_id, kind, amount, balance_before, balance_after, reference)
    VALUES (uid, 'game', -_amount, bal, bal - _amount, 'wheel:bet:' || _slot_key);

  INSERT INTO public.wheel_bets (round_id, user_id, room_id, slot_key, amount)
    VALUES (r.id, uid, _room_id, _slot_key, _amount) RETURNING * INTO b;
  RETURN b;
END $$;